OANDA:
  API: "api-fxpractice.oanda.com"
  ACCESS_TOKEN: "12345678900987654321-abc34135acde13f13530"
  ACCOUNT_ID: "xxx-xxx-xxxxxxxx-001"
  PORT: 443

QUANTUMHEDGE:
  LISENCE: "s3az29vbx5w3"
  PORT: 443
  ACCOUNT_ID: "aaa"

#OANDA:
  #LIVE_API: "api-fxtrade.oanda.com"
  #PRACTICE_API: "api-fxpractice.oanda.com"
  #ACCESS_TOKEN: "12345678900987654321-abc34135acde13f13530"
  #DEFAULT_ACCOUNT_ID: "xxx-xxx-xxxxxxxx-001"
  #PORT: 443

